import { name } from './constants'

export const SET_MAP_CENTER = `${name}/SET_MAP_CENTER`
export const SET_SELECTED_CLUSTER = `${name}/SET_SELECTED_CLUSTER`

export const FETCH_CLUSTERS_REQUEST = `${name}/FETCH_CLUSTERS_REQUEST`
export const FETCH_CLUSTERS_SUCCESS = `${name}/FETCH_CLUSTERS_SUCCESS`
export const FETCH_CLUSTERS_FAILURE = `${name}/FETCH_CLUSTERS_FAILURE`

export const FETCH_DEPOTS_REQUEST = `${name}/FETCH_DEPOTS_REQUEST`
export const FETCH_DEPOTS_SUCCESS = `${name}/FETCH_DEPOTS_SUCCESS`
export const FETCH_DEPOTS_FAILURE = `${name}/FETCH_DEPOTS_FAILURE`

export const FETCH_RIDERS_REQUEST = `${name}/FETCH_RIDERS_REQUEST`
export const FETCH_RIDERS_SUCCESS = `${name}/FETCH_RIDERS_SUCCESS`
export const FETCH_RIDERS_FAILURE = `${name}/FETCH_RIDERS_FAILURE`

export const SET_RIDER_REQUEST = `${name}/SET_RIDER_REQUEST`
export const SET_RIDER_SUCCESS = `${name}/SET_RIDER_SUCCESS`
export const SET_RIDER_FAILURE = `${name}/SET_RIDER_FAILURE`
