import { name } from './constants'

export const SET_MAP_CENTER = `${name}/SET_MAP_CENTER`
export const SET_SELECTED_CLUSTER = `${name}/SET_SELECTED_CLUSTER`
export const SET_SEARCH_CLUSTER = `${name}/SET_SEARCH_CLUSTER`
export const SET_FILTER_CLUSTER = `${name}/SET_FILTER_CLUSTER`

export const FETCH_CLUSTERS_REQUEST = `${name}/FETCH_CLUSTERS_REQUEST`
export const FETCH_CLUSTERS_SUCCESS = `${name}/FETCH_CLUSTERS_SUCCESS`
export const FETCH_CLUSTERS_FAILURE = `${name}/FETCH_CLUSTERS_FAILURE`

export const FETCH_DEPOTS_REQUEST = `${name}/FETCH_DEPOTS_REQUEST`
export const FETCH_DEPOTS_SUCCESS = `${name}/FETCH_DEPOTS_SUCCESS`
export const FETCH_DEPOTS_FAILURE = `${name}/FETCH_DEPOTS_FAILURE`

export const FETCH_RIDERS_REQUEST = `${name}/FETCH_RIDERS_REQUEST`
export const FETCH_RIDERS_SUCCESS = `${name}/FETCH_RIDERS_SUCCESS`
export const FETCH_RIDERS_FAILURE = `${name}/FETCH_RIDERS_FAILURE`

export const UPDATE_CLUSTER_REQUEST = `${name}/UPDATE_CLUSTER_REQUEST`
export const UPDATE_CLUSTER_SUCCESS = `${name}/UPDATE_CLUSTER_SUCCESS`
export const UPDATE_CLUSTER_FAILURE = `${name}/UPDATE_CLUSTER_FAILURE`

export const CUT_OFF_REQUEST = `${name}/CUT_OFF_REQUEST`
export const CUT_OFF_SUCCESS = `${name}/CUT_OFF_SUCCESS`
export const CUT_OFF_FAILURE = `${name}/CUT_OFF_FAILURE`

export const FETCH_STATS_REQUEST = `${name}/FETCH_STATS_REQUEST`
export const FETCH_STATS_SUCCESS = `${name}/FETCH_STATS_SUCCESS`
export const FETCH_STATS_FAILURE = `${name}/FETCH_STATS_FAILURE`

