import { name } from './constants'

export const FETCH_CLUSTERS_REQUEST = `${name}/FETCH_CLUSTERS_REQUEST`
export const FETCH_CLUSTERS_SUCCESS = `${name}/FETCH_CLUSTERS_SUCCESS`
export const FETCH_CLUSTERS_FAILURE = `${name}/FETCH_CLUSTERS_FAILURE`

export const SELECT_CLUSTER = `${name}/SELECT_CLUSTER`
export const UNSELECT_CLUSTER = `${name}/UNSELECT_CLUSTER`

export const CHANGE_STATUS_REQUEST = `${name}/CHANGE_STATUS_REQUEST`
export const CHANGE_STATUS_SUCCESS = `${name}/CHANGE_STATUS_SUCCESS`
export const CHANGE_STATUS_FAILURE = `${name}/CHANGE_STATUS_FAILURE`

export const START_CLUSTER_DELIVERY_REQUEST = `${name}/START_CLUSTER_DELIVERY_REQUEST`
export const START_CLUSTER_DELIVERY_SUCCESS = `${name}/START_CLUSTER_DELIVERY_SUCCESS`
export const START_CLUSTER_DELIVERY_FAILURE = `${name}/START_CLUSTER_DELIVERY_FAILURE`

