import { name } from './constants'

export const FETCH_REQUEST = `${name}/FETCH_REQUEST`
export const FETCH_SUCCESS = `${name}/FETCH_SUCCESS`
export const FETCH_FAILURE = `${name}/FETCH_FAILURE`

export const FETCH_USERS_REQUEST = `${name}/FETCH_USERS_REQUEST`
export const FETCH_USERS_SUCCESS = `${name}/FETCH_USERS_SUCCESS`
export const FETCH_USERS_FAILURE = `${name}/FETCH_USERS_FAILURE`

export const CREATE_USER_REQUEST = `${name}/CREATE_USER_REQUEST`
export const CREATE_USER_SUCCESS = `${name}/CREATE_USER_SUCCESS`
export const CREATE_USER_FAILURE = `${name}/CREATE_USER_FAILURE`

export const DELETE_USER_REQUEST = `${name}/DELETE_USER_REQUEST`
export const DELETE_USER_SUCCESS = `${name}/DELETE_USER_SUCCESS`
export const DELETE_USER_FAILURE = `${name}/DELETE_USER_FAILURE`

export const UPDATE_USER_REQUEST = `${name}/UPDATE_USER_REQUEST`
export const UPDATE_USER_SUCCESS = `${name}/UPDATE_USER_SUCCESS`
export const UPDATE_USER_FAILURE = `${name}/UPDATE_USER_FAILURE`

export const FETCH_WRITERS_REQUEST = `${name}/FETCH_WRITERS_REQUEST`
export const FETCH_WRITERS_SUCCESS = `${name}/FETCH_WRITERS_SUCCESS`
export const FETCH_WRITERS_FAILURE = `${name}/FETCH_WRITERS_FAILURE`

export const CREATE_WRITER_REQUEST = `${name}/CREATE_WRITER_REQUEST`
export const CREATE_WRITER_SUCCESS = `${name}/CREATE_WRITER_SUCCESS`
export const CREATE_WRITER_FAILURE = `${name}/CREATE_WRITER_FAILURE`

export const DELETE_WRITER_REQUEST = `${name}/DELETE_WRITER_REQUEST`
export const DELETE_WRITER_SUCCESS = `${name}/DELETE_WRITER_SUCCESS`
export const DELETE_WRITER_FAILURE = `${name}/DELETE_WRITER_FAILURE`

export const UPDATE_WRITER_REQUEST = `${name}/UPDATE_WRITER_REQUEST`
export const UPDATE_WRITER_SUCCESS = `${name}/UPDATE_WRITER_SUCCESS`
export const UPDATE_WRITER_FAILURE = `${name}/UPDATE_WRITER_FAILURE`

export const CHANGE_SELECTED_ROLE = `${name}/CHANGE_SELECTED_ROLE`